name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:  ${{ secrets.CONTAINER_REGISTRY }}:${{ github.sha }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Deploy Stack
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |

              docker container stop ${{ secrets.CONTAINER_NAME }}
              
              docker rm ${{ secrets.CONTAINER_NAME }}

              docker pull ${{ secrets.CONTAINER_REGISTRY }}:${{ github.sha }}
         
              docker run -d --name ${{ secrets.CONTAINER_NAME }} --network ${{ secrets.NETWORK }} -p ${{ secrets.CONTAINER_PORT }} -t ${{ secrets.CONTAINER_REGISTRY }}:${{ github.sha }}
